version: '3'

services:
  valheim:
    container_name: valheim
    image: lloesche/valheim-server
    ports:
      - '2456-2458:2456-2458/udp'
    volumes:
      - vallheim-config:/config
      - valheim-dl:/opt/valheim_dl
      - valheim-runtime:/opt/valheim
      - ./patches/bin/valheim-updater.sh:/usr/local/bin/valheim-updater
      - ./patches/supervisor_updater.conf:/etc/supervisor/conf.d/supervisor_updater.conf
    environment:
      SERVER_NAME: $SERVER_NAME
      SERVER_PASS: $PASSWORD
      WORLD_NAME: $WORLD
      SKIP_AUTOUPDATES: $SKIP_AUTOUPDATES

volumes:
  vallheim-config:
  valheim-runtime:
  valheim-dl:
