version: "3.9"
services: 
  valheim: 
    image: lloesche/valheim-server
    volumes: 
      - vallheim-config:/config
      - valheim-gamedata:/opt/valheim
    ports: 
      - "2456-2458:2456-2458/udp" 
    environment: 
      - SERVER_NAME=$SERVER_NAME
      - SERVER_PASS=$PASSWORD
      - WORLD_NAME=$WORLD
      - SERVER_PUBLIC=1

volumes:
  vallheim-config:
    driver: local
  valheim-gamedata:
    driver: local
