version: '3'

services:
  vallheim:
    container_name: vallheim
    image: lloesche/valheim-server
    ports:
      - '2456-2458:2456-2458/udp'
    volumes:
      - vallheim-config:/config
    environment:
      SERVER_NAME: $SERVER_NAME
      SERVER_PASS: $PASSWORD
      WOLRD_NAME: $WORLD

volumes:
  vallheim-config:
