version: '3'

services:
  vallheim:
    container_name: vallheim
    image: lloesche/valheim-server
    ports:
      - '2456-2458:2456-2458/udp'
    volumes:
      - vallheim-config:/config
      - ./patches/bin/vallheim-updater.sh:/usr/local/bin/vallheim-updater
      #- ./patches/supervisor_updater.conf:/etc/supervisor.d/supervisor_updater.conf
    environment:
      SERVER_NAME: $SERVER_NAME
      SERVER_PASS: $PASSWORD
      WORLD_NAME: $WORLD
      SKIP_AUTOUPDATES: $SKIP_AUTOUPDATES

volumes:
  vallheim-config:
